### ISSUE TITLE
Error messages in Godot 3.1

### ISSUE THREAD

**Issue by bborncr** [Superwaitsum/GDSerialAsset#1]
Godot 3.1
Windows 10

Thanks for this code! It's working fine. However, there are some error messages:
```
modules/gdnative/gdnative.cpp:488 - No valid library handle, can't get symbol from GDNative object
modules/gdnative/gdnative.cpp:393 - No valid library handle, can't terminate GDNative object
```

**Comment by kmare** [comment]
I'm getting these errors too with Godot 3.1, on Linux.

**Comment by kmare** [comment]
Using godot 3.1.1 and recompiling the GDSercomm library made the errors go away and it looks like it's working fine.
@Superwaitsum  thank you for the great library btw!

**Comment by bborncr** [comment]
I don't get the error anymore in Godot 3.1.1 either.
